# Site settings
title: Troutt025 ePortfolio
author: Jesse Troutt
  name: Jesse Troutt
  email: Troutt025@gmail.com
description: "ePortfolio for Troutt025"

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
